"""add nickname

Revision ID: b60c87ea3311
Revises: 
Create Date: 2025-06-29 18:54:47.603006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60c87ea3311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_nickname'), ['nickname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nickname'))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
