"""delete nickname

Revision ID: c4bc3860e289
Revises: 6bcce3a4a034
Create Date: 2025-06-29 23:50:31.118147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4bc3860e289'
down_revision = '6bcce3a4a034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nickname'))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_nickname'), ['nickname'], unique=True)

    # ### end Alembic commands ###
